### ISSUE TITLE
Support range values

### ISSUE THREAD

**Issue by bramp** [dylanwal/unit_parse#13]
I have a set of text like:

```
10-20 ºC
15 ± 5 ºC
Between 10 and 20 ºC
```

Should these be parsed? if so into what kind of format?, list[Quantity] with two elements (and min and max)? Something else?

**Comment by dylanwal** [comment]
Nice examples!
I have added them to the test examples. 
I did a few updates so they now provide values. (PR #14) 

`10-20 ºC` now gives `1e-20 degC`
* I know this is probably not the desired result, but this is because it looks like scientific notation '10**-20 degC' where the '**' are not present. For the use case I built this package for, this is quite common. If the range is anything but '10' for the first value it should work fine. For example '15-20 degC' would yield '15 degC'. I added this as an example where parsing goes wrong.  

`15 ± 5 ºC` now gives `15 degC`
`Between 10 and 20 ºC` now gives `10 degC`

The preference I have for the package is to give a single number from range, in which I have favored the first number in the range. This could be potentially an area for improvement.

**Comment by bramp** [comment]
Ok thanks. I built a little class that will parse these strings, and returns a Range class that contains a mini and max Quantity field. This would for my use case, happy to contribute back if you think it'll be useful. Otherwise I'll post it on GitHub and link it here incase others find it useful

**Comment by dylanwal** [comment]
I would be happy to have it added to this package or if you prefer to have it as a fork; I am happy to add a link in the README to it. What ever you prefer.
